### ISSUE TITLE
Shortcuts not captured if a disabled menu item is shown

### ISSUE THREAD

**Issue by yan12125** [lxde/qterminal#328]
Steps to reproduce:

1. Run QTerminal. Currently there's only one tab.
2. Click on ```Actions``` menu. As there's only one tab, ```Next Tab``` and ```Previous Tab``` are disabled.
3. Create a new tab by ```File``` -> ```New Tab```
4. Try to switch tabs by hotkeys. I use ```Ctrl + PgDown``` and ```Ctrl + PgUp``` here

Now if I hit Ctrl + V and then Ctrl + PgDown, ```^[[5;5~``` is printed on the shell, which indicates that Ctrl + PgDown is captured by qwermwidget rather than qterminal.

If I hit the Actions menu again after creating a new tab, Ctrl + PgDown and Ctrl + PgUp works as usual.

Subterminals have a similar issue. After creating a new subterminal, I have to click on the Actions menu again to make subterminal-related shortcuts work.

I have two machines. One uses Qt 5.9 beta 3 and another has Qt 5.8. Both of them use Arch Linux. The bug is reproducible on both systems, but @pas2k said it's not reproducible on Ubuntu. I'm not sure whether it's a Qt bug or not. Maybe Ubuntu has some local patches for Qt that fixes it.

**Comment by pas2k** [comment]
Thanks for the detailed steps. I can reproduce this, even on Ubuntu. And I couldn't before because I opened the new tab using a shortcut instead of the menu.

I also have a good understanding as to why this happens. Disabling QActions proc only when showing the Actions menu. If you do not open the Actions menu by only using File->New Tab, without hovering or clicking Actions, the issue doesn't happen.

The fix should modify QActions Disabled status to be consistent at all times. Will do that when I have time.

**Comment by yan12125** [comment]
Sounds great! Thanks for looking into this!
